#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'calculadora_service_types'

module CalculadoraRemota
  class Client
    include ::Thrift::Client

    def add(number1, number2)
      send_add(number1, number2)
      return recv_add()
    end

    def send_add(number1, number2)
      send_message('add', Add_args, :number1 => number1, :number2 => number2)
    end

    def recv_add()
      result = receive_message(Add_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'add failed: unknown result')
    end

    def subtract(number1, number2)
      send_subtract(number1, number2)
      return recv_subtract()
    end

    def send_subtract(number1, number2)
      send_message('subtract', Subtract_args, :number1 => number1, :number2 => number2)
    end

    def recv_subtract()
      result = receive_message(Subtract_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'subtract failed: unknown result')
    end

    def multiply(number1, number2)
      send_multiply(number1, number2)
      return recv_multiply()
    end

    def send_multiply(number1, number2)
      send_message('multiply', Multiply_args, :number1 => number1, :number2 => number2)
    end

    def recv_multiply()
      result = receive_message(Multiply_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'multiply failed: unknown result')
    end

    def divide(number1, number2)
      send_divide(number1, number2)
      return recv_divide()
    end

    def send_divide(number1, number2)
      send_message('divide', Divide_args, :number1 => number1, :number2 => number2)
    end

    def recv_divide()
      result = receive_message(Divide_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'divide failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_add(seqid, iprot, oprot)
      args = read_args(iprot, Add_args)
      result = Add_result.new()
      result.success = @handler.add(args.number1, args.number2)
      write_result(result, oprot, 'add', seqid)
    end

    def process_subtract(seqid, iprot, oprot)
      args = read_args(iprot, Subtract_args)
      result = Subtract_result.new()
      result.success = @handler.subtract(args.number1, args.number2)
      write_result(result, oprot, 'subtract', seqid)
    end

    def process_multiply(seqid, iprot, oprot)
      args = read_args(iprot, Multiply_args)
      result = Multiply_result.new()
      result.success = @handler.multiply(args.number1, args.number2)
      write_result(result, oprot, 'multiply', seqid)
    end

    def process_divide(seqid, iprot, oprot)
      args = read_args(iprot, Divide_args)
      result = Divide_result.new()
      result.success = @handler.divide(args.number1, args.number2)
      write_result(result, oprot, 'divide', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Add_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NUMBER1 = 1
    NUMBER2 = 2

    FIELDS = {
      NUMBER1 => {:type => ::Thrift::Types::I32, :name => 'number1'},
      NUMBER2 => {:type => ::Thrift::Types::I32, :name => 'number2'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Add_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Subtract_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NUMBER1 = 1
    NUMBER2 = 2

    FIELDS = {
      NUMBER1 => {:type => ::Thrift::Types::I32, :name => 'number1'},
      NUMBER2 => {:type => ::Thrift::Types::I32, :name => 'number2'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Subtract_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Multiply_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NUMBER1 = 1
    NUMBER2 = 2

    FIELDS = {
      NUMBER1 => {:type => ::Thrift::Types::I32, :name => 'number1'},
      NUMBER2 => {:type => ::Thrift::Types::I32, :name => 'number2'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Multiply_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Divide_args
    include ::Thrift::Struct, ::Thrift::Struct_Union
    NUMBER1 = 1
    NUMBER2 = 2

    FIELDS = {
      NUMBER1 => {:type => ::Thrift::Types::I32, :name => 'number1'},
      NUMBER2 => {:type => ::Thrift::Types::I32, :name => 'number2'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Divide_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::DOUBLE, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

